# Generated by Django 4.0.3 on 2022-05-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recipe_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
